f1=input()
int1=input()
str1=input()
a=float(f1)
print("%.2f"%a)
print("%e %E %.2f%%"%(a, a, a*100))
print("{0:b}".format(int(int1)), end="")  
print(" %x"%int(int1))
c=str.strip(str1)
print(str.upper(c))
print("%20s"%c)
print(c.center(20, "*"))  
print("{} + {} = {}".format(a, int(int1), a+int(int1)))
